version: '3.8'
services:
  mysql-server:
    image: "${MYSQL_IMAGE}:${MYSQL_IMAGE_TAG}"
    command:
    - mysqld
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_bin
    restart: "${RESTART_POLICY}"
    ports:
      - 3307:3306
    volumes:
    - ${DATA_DIRECTORY}/var/lib/mysql:/var/lib/mysql:rw
  #   - dbsocket:/var/run/mysqld/
    env_file:
    - ${ENV_VARS_DIRECTORY}/.env_db_mysql
    secrets:
    - MYSQL_USER
    - MYSQL_PASSWORD
    - MYSQL_ROOT_PASSWORD
    stop_grace_period: 1m
    networks:
      zbx_net_database:
        aliases:
          - mysql-server

  zabbix-server:
    image: "${ZABBIX_SERVER_MYSQL_IMAGE}:${ZABBIX_ALPINE_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"

    depends_on:
      - mysql-server

    ports:
      - "${ZABBIX_SERVER_PORT}:10051"
    restart: "${RESTART_POLICY}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIRECTORY}/etc/zabbix/zabbix_agentd.d/:/etc/zabbix/zabbix_agentd.d/
      - ${DATA_DIRECTORY}/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ${DATA_DIRECTORY}/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ${DATA_DIRECTORY}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      # - snmptraps:/var/lib/zabbix/snmptraps:ro
    tmpfs: /tmp
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
        #    deploy:
        #      resources:
        #        limits:
        #          cpus: '0.70'
        #          memory: 1G
        #        reservations:
        #          cpus: '0.5'
        #          memory: 512M
    env_file:
    - ${ENV_VARS_DIRECTORY}/.env_srv
    - ${ENV_VARS_DIRECTORY}/.env_db_mysql
    networks:
      zbx_net_database:
        aliases:
          - zabbix-server
      zbx_net_backend:
        aliases:
          - zabbix-server
          - zabbix-server-mysql
      zbx_net_frontend:

    secrets:
    - MYSQL_USER
    - MYSQL_PASSWORD
    - MYSQL_ROOT_USER
    - MYSQL_ROOT_PASSWORD

  zabbix-web-nginx-mysql:
    image: "${ZABBIX_WEB_NGINX_MYSQL_IMAGE}:${ZABBIX_ALPINE_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    ports:
      - "${ZABBIX_WEB_NGINX_HTTP_PORT}:8080"
      - "${ZABBIX_WEB_NGINX_HTTPS_PORT}:8443"
    restart: "${RESTART_POLICY}"
    depends_on:
      - mysql-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIRECTORY}/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ${DATA_DIRECTORY}/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    tmpfs: /tmp
    #    deploy:
    #      resources:
    #        limits:
    #          cpus: '0.70'
    #          memory: 512M
    #        reservations:
    #          cpus: '0.5'
    #          memory: 256M
    env_file:
      - ${ENV_VARS_DIRECTORY}/.env_web
      - ${ENV_VARS_DIRECTORY}/.env_db_mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_database:
      zbx_net_backend:
        aliases:
          - zabbix-web-nginx-mysql
      zbx_net_frontend:
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD

  zabbix-agent:
    image: "${ZABBIX_AGENT_IMAGE}:${ZABBIX_ALPINE_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    ports:
      - "${ZABBIX_AGENT_PORT}:10050"
    restart: "${RESTART_POLICY}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIRECTORY}/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    tmpfs: /tmp
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
      mode: global
    env_file:
      - ${ENV_VARS_DIRECTORY}/.env_agent
    privileged: true
    pid: "host"
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-agent
          - zabbix-agent-passive
    stop_grace_period: 5s

# Datasource: http://zabbix-web-nginx-mysql:8080/api_jsonrpc.php
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      zbx_net_database:
      zbx_net_backend:
        aliases:
          - zabbix-web-nginx-mysql
      zbx_net_frontend:
    links:
      - mysql-server
      - zabbix-server
    restart: always
    user:  "${UID}:${GID}"
    volumes:
      - '${DATA_DIRECTORY}/grafana-data:/var/lib/grafana:rw'
      - ${ENV_VARS_DIRECTORY}/grafana/config:/etc/grafana-config
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app, grafana-clock-panel
      - GF_SERVER_ROOT_URL=http://monitor-grafana.ramper.com.br/
      - GF_AUTH_ANONYMOUS_ENABLED=true

    depends_on:
      - mysql-server
      - zabbix-server




networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "${FRONTEND_ENABLE_IPV6}"
    ipam:
      driver: "${FRONTEND_NETWORK_DRIVER}"
      config:
      - subnet: "${FRONTEND_SUBNET}"
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "${BACKEND_ENABLE_IPV6}"
    internal: true
    ipam:
      driver: "${BACKEND_NETWORK_DRIVER}"
      config:
      - subnet: "${BACKEND_SUBNET}"
  zbx_net_database:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "${DATABASE_NETWORK_ENABLE_IPV6}"
    internal: false
    ipam:
      driver: "${DATABASE_NETWORK_DRIVER}"

secrets:
  MYSQL_USER:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_ROOT_PASSWORD
